### ISSUE TITLE
Resetting the game can put a monster into the next stage

### ISSUE THREAD

**Issue by twilightpuma** [rex8112/necronursery#10]
Resetting the game after clicking give on a monster will allow you to complete its next stage.

**To Reproduce**
1. Plant monster
2. Reset game
3. Open game back up
4. Click give
5. Redo steps 2-4 until monster is complete

**Environment:**
 - Android

**Comment by rex8112** [comment]
Test this again @twilightpuma, it might've been fixed with 36266fc93d1c6f8221584e120cb6f11432dde546
